### ISSUE TITLE
State check

### ISSUE THREAD

**Issue by krizajb** [LeoFuso/actuator-kafka-streams#14]
Wouldn't it make more sense to check only for RUNNING state? This way one can query store right away after readiness is UP? With current implementation, readiness is UP but if kafka stream state is still REBALANCING, making the store unavailable.

**Comment by LeoFuso** [comment]
Hey!

Are you talking about the Health Check, overall, or just the Queriable Store portion?

**Comment by LeoFuso** [comment]
Oh, I see it.

https://github.com/LeoFuso/actuator-kafka-streams/blob/main/src/main/java/io/github/leofuso/autoconfigure/actuator/kafka/streams/health/KStreamsHealthIndicator.java#L125

When the Streams App starts, the first thing it does is recover its remote state by reading the changelog topic, right? 

When the Stream Thread is performing its recovery, it reports as Rebalancing. A StreamThread is only Ready when it's consuming from its designated topic and partition.

If I report Up only when the StreamThread is ready, and use this Health Check to report to the Kubernetes cluster about the state of the Pod, I will eventually drop the Pod, even though there's nothing wrong with it.

**Comment by krizajb** [comment]
Correct, well I was reading about the Kafka HealthIndicator, why it is missing in springboot and it does make sense. Every application has it own needs, hence no standard implementation.

**Comment by LeoFuso** [comment]
Yeah, but there's an implementation of this health check in the Spring Cloud project.

The Spring Kafka vanilla implementation has the capability of auto remover if the broker it's connected to goes down, the Kafka Streams API doesn't. Hence, this implementation.

**Comment by LeoFuso** [comment]
Here, 
Take a look!

https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/main/spring-cloud-stream-binder-kafka-streams/src/main/java/org/springframework/cloud/stream/binder/kafka/streams/KafkaStreamsBinderHealthIndicator.java#L129

**Comment by krizajb** [comment]
Hehe, thanks, I had a look before and changed my humble implementation to do the same for the time being :)
